apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - "./ip-pool.yaml"

helmCharts:
  - name: cilium
    repo: https://helm.cilium.io
    version: 1.13.1
    releaseName: "cilium"
    valuesFile: values.yaml