apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

patchesStrategicMerge: 
  - patches/hubble-ui-service.yaml

resources:
  - ip-pool.yaml
  - ip-advertisement.yaml

helmCharts:
  - name: cilium
    repo: https://helm.cilium.io
    version: 1.14.2
    releaseName: "cilium"
    valuesFile: values.yaml