# This needs to be set for the coredns to be used
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: policy-kube-system-namespace
  namespace: kube-system
spec:
  endpointSelector: {}

  ingress:
  - fromEntities:
    - all

  egress:
  - toEntities:
    - all