debug:
  enabled: true

k8sServiceHost: 192.168.0.23
k8sServicePort: 6443

# Needs to be "strict" for cilium to work
kubeProxyReplacement: strict

loadBalancer: 
  l7:
    # Applicable values: round_robin, least_request, random
    algorithm: "round_robin"

# Make LoadBalancers accesible from local network
l2announcements:
  enabled: true
externalIPs:
  enabled: true

hubble:
  ui:
    enabled: true
    rollOutPods: true

  relay:
    enabled: true
    rollOutPods: true
