debug:
  enabled: true

# This tells cilium to only allow traffic that 
# has explicitly been allowed by a policy
policyEnforcementMode: "strict"

k8sServiceHost: 192.168.0.23
k8sServicePort: 6443

# Needs to be "strict" for cilium to work
kubeProxyReplacement: "strict"

loadBalancer: 
  l7:
    # Applicable values: round_robin, least_request, random
    algorithm: "round_robin"

# Make LoadBalancers accesible from local network
l2announcements:
  enabled: true
externalIPs:
  enabled: true

tls:
  enabled: false

hubble:
  enabled: true
  ui:
    enabled: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: cloudflare-issuer
      hosts:
        - hubble.valley.no
  relay:
    enabled: true

# MTLS

authentication:
  mutual:
    # -- Port on the agent where mutual authentication handshakes between agents will be performed
    port: 4250
    # -- Timeout for connecting to the remote node TCP socket
    connectTimeout: 5s
    # Settings for SPIRE
    spire:
      # -- Enable SPIRE integration (beta)
      enabled: true
      # -- Annotations to be added to all top-level spire objects (resources under templates/spire)
      annotations: {}
      # Settings to control the SPIRE installation and configuration
      install:
        # -- Enable SPIRE installation.
        # This will only take effect only if authentication.mutual.spire.enabled is true
        enabled: true
        # -- SPIRE namespace to install into
        namespace: cilium-spire
