apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcp-nlp
  namespace: perceptiq
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: gcp-nlp
  data:
    - secretKey: sa-key.json
      remoteRef:
        key: gcp-nlp
        property: sa-key.json
