apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: default
  source:
    path: layer0/apps/external-secrets
    repoURL: https://github.com/s1monb/homelab.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
