apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: messaging
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: nats
    repoURL: https://nats-io.github.io/k8s/helm/charts/
    targetRevision: 2.14.5
    helm:
      releaseName: nats
      values: |
        config:
          cluster:
            enabled: false
          jetstream:
            enabled: true
            fileStore:
              enabled: true
              maxSize: 18Gi
              pvc:
                enabled: true
                size: 20Gi
                storageClassName: local-path

          nats:
            port: 4222

          merge:
            authorization:
              users:
                - user: << $NATS_USER >>
                  password: << $NATS_PASSWORD >>

        container:
          env:
            NATS_USER:
              valueFrom:
                secretKeyRef:
                  name: nats-auth
                  key: username
            NATS_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: nats-auth
                  key: password
            GOMEMLIMIT: 800MiB
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi

        promExporter:
          enabled: true
          podMonitor:
            enabled: true

        natsBox:
          enabled: true
          container:
            env:
              NATS_USER:
                valueFrom:
                  secretKeyRef:
                    name: nats-auth
                    key: username
              NATS_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: nats-auth
                    key: password

        statefulSet:
          merge:
            spec:
              persistentVolumeClaimRetentionPolicy:
                whenDeleted: Retain
                whenScaled: Retain

        podTemplate:
          configChecksumAnnotation: true
          terminationGracePeriodSeconds: 60

        podDisruptionBudget:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
