apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: prometheus-node-exporter
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 4.52.1
    helm:
      releaseName: node-exporter
      values: |
        fullnameOverride: node-exporter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
