apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ollama-operator-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/nekomeowww/ollama-operator.git
    path: dist
    targetRevision: v0.10.10
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
