apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onepassword-connect
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: connect
    repoURL: https://1password.github.io/connect-helm-charts
    targetRevision: 1.17.1
    helm:
      releaseName: onepassword-connect
      values: |
        connect:
          credentialsName: onepassword-connect-credentials
          credentialsKey: 1password-credentials.json
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
