apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: perceptiq-lab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: perceptiq-lab
    server: https://kubernetes.default.svc
  project: default
  source:
    path: layer0/apps/perceptiq-lab
    repoURL: https://github.com/s1monb/homelab.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
