apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tandoor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: tandoor
    server: https://kubernetes.default.svc
  project: default
  source:
    path: layer0/apps/tandoor
    repoURL: https://github.com/s1monb/homelab.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
