apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: excalidraw-data
  namespace: excalidraw
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
