# This needs to be set for the coredns to be used
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-sealed-secrets
  namespace: kube-system
spec:
  endpointSelector:
    matchLabels:
      "app.kubernetes.io/name": sealed-secrets
  ingress:
  - fromEntities:
    - cluster
  egress:
  - toEntities:
    - cluster