apiVersion: v1
kind: Service
metadata:
  name: mimir
  namespace: monitoring
  labels:
    app.kubernetes.io/name: mimir
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mimir
  ports:
    - name: http
      port: 9009
      targetPort: http
      protocol: TCP
