apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - sealed-1password-credentials.yaml
  - sealed-1password-token.yaml

helmCharts:
  - name: connect
    repo: https://1password.github.io/connect-helm-charts
    version: 1.16.0
    releaseName: "connect"
    includeCRDs: true
    namespace: onepassword
    valuesFile: values.yaml
