---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: onepassword-token
  namespace: onepassword
spec:
  encryptedData:
    token: AgB4WunX7NUEBnI8XklCAvSWXfpfIMzjEvxPzu61p/cdJX/EUWeo67UZenKnufim2XsA/m5wzYYVT5xzNipKUIkSyuQ6wlAsIIQZZ2+4nDqITiQ90P1MsM1LpLiPaMdbC+yxBvWmfV/IOveFWlZSVW+fgqh/grBwtm7YxBKhHkVJra9eGJcsiS2wzHVdbgGg1tEIbmjL9wJgU+9nNrKwP43xk0uv04caKuVhzAp6E9BhAPBwRx1iylc5wtE7pz+pY8r19CvV6M6NFqik6RWtLX0JKU6HUjIjOJVkLv3dzS6vPZurL1EAA/uGIJjPvlVeysdIj9yVQG0Qdjyu2ygStbsl4j+9GuxAIgdqtElF/nOJrPNAMrgx9gcURDE666Xf9vsiWu8JLux/kc07dWRO+Hw9QA0eDzBMyWEh0ySAupvuxDFIUpbVmrMMdc7VNAyQYkr7nsgzzF+CBfJwyMaO7BeN1zEIC4Mx/sEXOb1qNhi7LASt8QCkAUgdt+xgHQB5sftZtV9qhNMhlO3UJ6jMt7ALaKqvYv3EZ81I5u58uwcfGuEELM7rcgzm66sV9rXl91uovEfZDx3w2BanpAW+9+W6K4VgTy3Pnfl5XLW4jD/ia51JWk8tQdNVYJ9Ev1uE/zpiS9VloTDGKaHEwnHVpTVCHSSGecRqcJ1Jp9FoNl4obfBawrqZxz8yjAVCDhQMEzVBVwOWHTxjKSlAc4qUPynE8F+VlMkI6hb5uX857UKrpmTXfclckgDJGrA1uz9OQR7WZe2hxa5sWO5w3VSEBI3oo9dKpu1fUy1D73+V4oIdLxc+QtZK+A9wRfYh13rayb6Pv31yxivkAIUgK5idmBHhqZ3u0qBG2nGyaraZ743nsyn31FIVsBYe1MqHWfgTcbzYZymg1GfoDmd87y6LqKhIj8tYoJuJTuMGVMvRjKayCA/HAXL2+TdyuRTCI26X1KjONofrhB4ZBZHs3lvBrPp6UvCo/xcXL4W11/ki4SYUymJqjWeCuTm2pmWiZlHXVd8V4McY9VMDF3E8evR3cqgglwZ3s9uEoQUNsN1R3XrScmotWcT4Gl7gacRNETaUvNi3ibllZK35q5d9AIZoeigCiYLYZeswGHy+AIxyDfsZIJx7Mmr3Qm1LyW1HHPoYBIzZz7nQ2QoV7bhJHiTiB+v/wwN8GZK4Eyt4fVvxGyrnVAuDTECYSV3ik5tvY3Juw6DmY25w8WoBtO7xmVhe1tpItMUP/tEBL/ftDIVFmGaykHqJqod5WR3Jfr6e4wNUYw/SQZVwD6nttrx8UL66/1/9eCUErqUxGRGgJi1kg1fmRd3E1adtlNCVqgXEhZ+tVZYh1QAawjw+FZxaptrPGcO7mvnhhezOqEMflm06eBCqLQ3FtpX5U3LPuyO9COIhyidapdLWmFvrciFIYK1kHc2MjZscLi3u2s+2erXMFTwQB8XVJw1BW773rC05bubPCipGowlxavK46B7T6kBtVHZ7WVMZlNdkZAjL/A/GjbYZ30jHxu274aO+v/t2Bibv3Y/ksNutdTri/Qnaq2rjCXYCk5U=
  template:
    metadata:
      creationTimestamp: null
      name: onepassword-token
      namespace: onepassword
