---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: onepassword-token
  namespace: onepassword
spec:
  encryptedData:
    token: AgCLjeGntO8WwYqYOqFnY34UtPqo+3pNPemSChHKWlNKdUXs5LN15iZv7BjF/OyOZdgG5/xROl9Tp1Y2oCxN4XtdmOiHu7s0+MKsVZSbGLYNn5r+tNV5lR3mv6MPV0C5heDxiAEhSfaY43+QKcSjw6LcgJoMmi2VJrw3ErMgUBOxYiym/CwPLfKWWe3n/XyHruPPB0kS8pDa5LLc9T1iDWK4AtBG/b3kLx5uggPFuB7eP5atGUgLAq1ct6U9oiSzjVDtSfxs2NigauPYIfxgSqEmE5PXWh3FKEIuGi1msEt2E8BvAYFYRBKZ9dp7xSryr9uiJySvP51P+TeADFW2qlDOyjZJPWxBf0mpoYOX1ETUYdQOr2iWY4SMQHAyK37tqqy7a8Pmy+St4ecYIdfqzHPyaTjdHq/b1gJKrPbVTa+AU6v8cgodNj8j6ktbVP/mm4+y9q1cTi7DUZzrcliVHR29Az/27rrba33gDsReapLtl6fJuhDzC6F8G9HE49lZLawjn/KLoVgrGbBX4O6c+XOhqE56n46dXYvgXqpIGQNJK+XBqd5ldkjpEkmKzNeHQus296zBYAzC+36DpecopwMEzU8eDtXZMYwPM0La2+n/f0nHK03HkD4GDRf2yp/dcqO5lz3FJtqP7irDO+b6DBZ2o4wtotWM36ugKocJbnDB67zwTaem6NehQ0ItwSKc8V5mNu/8XOMveRltHyAvO/yf4ZbnxrR0JLdeYxxMDxkrjx5cJ4ipHrjKa/tKNG7Phgcj2Uhia7JEqWgVsPnzGPfexCLZgaiCdyy6ASj9WQg/kyFDYGtd3V46PWSlYUMd1Z+gUPAISChjrDObHBkS/TpQXi+NxHxvGtL/C+AAghImQle048hnAUSsdgQn8wXUWe0cX7/9DKOkD2PnPF8iISLir6B7+7rMo7zS3eddretUavcd+u7Y260Sx0ZdfImcho7V1KiHaW7rmR4Q1LVLR9wiqg9ml6knvUIMxpbR8pHTnkbVOeCAQyKdKcdKalrhxhnDKsFJgbsa7res2xaNDoPbb1jWNk06EdU7t+X6Duh5hDbY8hN3IpQb8r4z2sHmlWHhf9t/Y0xenJGbCGX289SzcH7Fpqn1p7GBjwbi8CrOACDa2qJmpQm39N4vMGUTQsZOmekpmW7UL60CTFZrEpk0Ki4vv02GOZRxTt9kk6Z8kusRR7DIoJuGxP71346exL8PjXMatwzqxoFOYoPj35Rq4WK89cwRUDOe/iUAp38vSt6BW8l8CtowWB5CFIZqnrolWnDhB+5askyCcATrVDsx3xyY+V1zwhJ/+uaLlL7ep22lIlE1xBzF6ZLwp37/8Xgnf3wKYYZOGeHK6ga+aYjtQ7aGo/2/PDYrwZG15Lk74X6xLrysiVWT34eJtXqbgdgyK3L4ZbmHPth/+yQsjVbvS1SKwh2s3v5QGE4r4mmUJ8CbUOFSdeSb35x4lEdbnDRwCplhIf0oUFyL6pJfGiKFtPIrTbqRTGLb+fWFuaL2/6XF+pGVDx/5PFBEztgQjdRxtfmVod2HQ8cRFjG2Apq3Q5f/
  template:
    metadata:
      creationTimestamp: null
      name: onepassword-token
      namespace: onepassword
