apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  namespace: onepassword
  name: onepassword-token
spec:
  itemPath: "vaults/dev-cluster/items/ds2boobuvdnfqxsd7agjqkyn2i"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  namespace: onepassword
  name: op-credentials-managed
spec:
  itemPath: "vaults/dev-cluster/items/kkno4eicbmxnaoxgx4dkowxsra"
