apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: onepassword-token
spec:
  itemPath: "vaults/dev-cluster/items/access-token"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: op-credentials
spec:
  itemPath: "vaults/dev-cluster/items/1password-credentials"
