apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
spec:
  project: app-of-apps
  source:
    path: kubernetes/dev-cluster/infra
    repoURL: https://github.com/s1monb/homelab
    targetRevision: HEAD
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
