apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik

resources:
  - namespace.yaml
  - cloudflare-certificate.yaml
  - allow-all-traffic.yaml
  - storageClass.yaml
  - persistentVolume.yaml
  - tlsstore.yaml


helmCharts:
  - name: traefik
    repo: https://helm.traefik.io/traefik
    version: 24.0.0
    releaseName: "traefik"
    includeCRDs: true
    valuesFile: values.yaml