apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: perceptiq-lab
  namespace: perceptiq-lab
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: cilium
  tls:
    - hosts:
        - perceptiq-lab.valley.no
      secretName: perceptiq-lab-valley-no-tls
  rules:
    - host: perceptiq-lab.valley.no
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: perceptiq-lab
                port:
                  number: 80
