apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sentry-secrets
  namespace: sentry
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: sentry-secrets
  data:
    - secretKey: admin-password
      remoteRef:
        key: sentry
        property: password
    - secretKey: clickhouse-password
      remoteRef:
        key: sentry
        property: clickhouse-password
