apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: perceptiq-secrets
  namespace: PREVIEW_NAMESPACE
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: perceptiq-secrets
  data:
    - secretKey: GOOGLE_PLACES_API_KEY
      remoteRef:
        key: perceptiq-testing
        property: GOOGLE_PLACES_API_KEY
    - secretKey: APIFY_TOKEN
      remoteRef:
        key: perceptiq-testing
        property: APIFY_TOKEN
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: perceptiq
        property: OPENAI_API_KEY
