apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd-chart
  namespace: argocd
spec:
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 9.4.0
    helm:
      releaseName: argo-cd
      values: |
        crds:
          annotations: 
            argocd.argoproj.io/sync-options: Replace=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true