apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: tandoor-db
  namespace: tandoor
spec:
  instances: 1
  storage:
    size: 5Gi
    storageClass: local-path
  bootstrap:
    initdb:
      database: tandoor
      owner: tandoor
