apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tandoor-media
  namespace: tandoor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
