apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBH3+xiGQQbBjOW2ClwSMZm+sgjV/zqFjNhaTgFvCQieEb3N7QK1FFuo4sbsREcQ+2EnNlC3CyiP+j8YH3rpbgtgmwTjAdgROhrV+SC1AcTor+kz/vktSlygIvjHZLSBR3tdxYZ6ugXiAeuUJRYvXOLC7ppdlTLDBTdPgD90A70u2v0M4bY5SHl9sXUhnQRL6jTrdeNESVZ78bKR1bQ7DaGbSoGuRjptignQqYqAyNpmVK4zmftoFyvjQnLQmtcRlLSienxd73V7UD9Ovj2vXCzD1u8o33A6uAfb+vJG6mZq83KWDyajqXwj8fIU7AfchKHXJAI0Uvke3ZTGCUaybd+VVKH5KGxyG3dI/FY8CruraEPV86vEj+b55CjqGVh6Sk9sflUt4NY7aOzIsg5gIRiiDVZK7F9LBSmK/cbOqmBNmshvJvCcO834heIpFuxHvNRrfFSC9yJ2dgudlsTXtrtZI2eDcoZ3Q8Dqx6e72IvsGeeGQCtgnlCwJTz/CS3lemRvGevtXo5HBCK6kkjaE7e6DNetb4ISlYoOMnMH5jsK/zfHVhc1rnR082CqwZCqLtb6Zg2SroeziIfx01Hv1J3zmbBZVnBVlA8wcsJTftYmJwPMdBFl31WR7Z9aUONxPIB7M1F2EUu3Ar2EWqyEkCX/5L1kDL2oJZMNSOJIZsLTBju4YcE6+FCIGvjXiee2UDut4Ra5pU0Wg8YcnPSGBOSFfgOdR2AbJYi8y8GHYVsMXl2n1NxRpif
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
