apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/s1monb/homelab
        revision: HEAD
        directories:
          - path: kubernetes/dev-cluster/infra/*
  template:
    metadata:
      name: "{{ path.basename }}"
    spec:
      project: default
      source:
        plugin:
          name: kustomize-build-with-helm
        repoURL: https://github.com/s1monb/homelab
        targetRevision: HEAD
        path: "{{ path }}"
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
