apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nats-auth
  namespace: messaging
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: nats-auth
  data:
    - secretKey: username
      remoteRef:
        key: nats
        property: username
    - secretKey: password
      remoteRef:
        key: nats
        property: password
