apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: grafana-admin
  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana
        property: username
    - secretKey: admin-password
      remoteRef:
        key: grafana
        property: password
